//! HTML rendering for decision reports.

use crate::pipeline::DecisionReport;
use truncore::core::TritValue;

pub fn render(report: &DecisionReport) -> String {
    format!(
        r#"<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aurora Report</title>
    <style>
        body {{ font-family: sans-serif; margin: 2rem; background: #111; color: #eee; }}
        h1 {{ color: #7cf; }}
        table {{ border-collapse: collapse; margin-top: 1rem; }}
        th, td {{ border: 1px solid #444; padding: 0.5rem 1rem; text-align: left; }}
        th {{ background: #222; }}
        .hold {{ color: #ff6; }}
        .true {{ color: #6f6; }}
        .false {{ color: #f66; }}
    </style>
</head>
<body>
    <h1>Aurora Decision Report</h1>
    <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>Input frequency</td><td>{input_freq:.3} Hz</td></tr>
        <tr><td>Detected frequency</td><td>{detected_freq:.3} Hz</td></tr>
        <tr><td>Embodied signal</td><td><span class="{embodied_class}">{embodied:?}</span> ({embodied_frame})</td></tr>
        <tr><td>Individual report</td><td><span class="{individual_class}">{individual:?}</span> ({individual_frame})</td></tr>
        <tr><td>Decision</td><td><span class="{result_class}">{result:?}</span> ({result_frame})</td></tr>
        <tr><td>Conflict</td><td>{conflict}</td></tr>
    </table>
    <p>Generated by Aurora v0.1.0 — M0 proof-of-concept.</p>
</body>
</html>"#,
        input_freq = report.input_freq,
        detected_freq = report.detected_freq,
        embodied_class = css_class(report.embodied.value()),
        embodied = report.embodied.value(),
        embodied_frame = report.embodied.frame(),
        individual_class = css_class(report.individual.value()),
        individual = report.individual.value(),
        individual_frame = report.individual.frame(),
        result_class = css_class(report.result.value()),
        result = report.result.value(),
        result_frame = report.result.frame(),
        conflict = if report.interrupt.is_some() {
            "Yes — cross-frame conflict detected"
        } else {
            "No"
        },
    )
}

fn css_class(value: TritValue) -> &'static str {
    match value {
        TritValue::True => "true",
        TritValue::False => "false",
        _ => "hold",
    }
}
