//! HTML rendering for decision reports — M0 attention-aware version.
//!
//! Renders: decision table, conflict panel, ASI gauge, reminder history.

use crate::bc::attention_guidance::{AttentionSession, UserResponse};
use crate::pipeline::DecisionReport;
use truncore::core::TritValue;

/// Render a full decision report as HTML, including attention data.
pub fn render(report: &DecisionReport, session: &AttentionSession) -> String {
    let conflict_section = render_conflict_panel(report);
    let attention_section = render_attention_section(report, session);
    let reminder_rows = render_reminder_rows(session);

    format!(
        r#"<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>Aurora Report — {scenario_id}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               margin: 2rem; background: #0d1117; color: #c9d1d9; }}
        h1 {{ color: #58a6ff; }}
        h2 {{ color: #7ee787; margin-top: 2rem; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }}
        table {{ border-collapse: collapse; margin-top: 1rem; width: 100%; max-width: 800px; }}
        th, td {{ border: 1px solid #30363d; padding: 0.6rem 1rem; text-align: left; }}
        th {{ background: #161b22; color: #8b949e; }}
        .hold {{ color: #d2991d; font-weight: bold; }}
        .true {{ color: #3fb950; font-weight: bold; }}
        .false {{ color: #f85149; font-weight: bold; }}
        .conflict-panel {{ background: #161b22; border: 1px solid #d2991d; border-radius: 6px;
                           padding: 1rem; margin-top: 1rem; max-width: 800px; }}
        .conflict-panel h3 {{ color: #d2991d; margin-top: 0; }}
        .no-conflict {{ background: #161b22; border: 1px solid #3fb950; border-radius: 6px;
                        padding: 1rem; margin-top: 1rem; max-width: 800px; }}
        .asi-gauge {{ display: flex; align-items: center; gap: 1rem; margin-top: 1rem; }}
        .asi-bar {{ flex: 1; height: 24px; background: #21262d; border-radius: 12px; overflow: hidden; }}
        .asi-fill {{ height: 100%; border-radius: 12px; transition: width 0.5s; }}
        .asi-value {{ font-size: 1.5rem; font-weight: bold; min-width: 4rem; text-align: right; }}
        .reminder {{ padding: 0.5rem; border-left: 3px solid #30363d; margin: 0.5rem 0; }}
        .reminder.shifted {{ border-left-color: #3fb950; }}
        .reminder.ignored {{ border-left-color: #f85149; }}
        .reminder.pending {{ border-left-color: #d2991d; }}
        footer {{ margin-top: 3rem; color: #484f58; font-size: 0.85rem; }}
    </style>
</head>
<body>
    <h1>Aurora Decision Report</h1>
    <table>
        <tr><th>Field</th><th>Value</th></tr>
        <tr><td>Input frequency</td><td>{input_freq:.3} Hz</td></tr>
        <tr><td>Detected frequency</td><td>{detected_freq:.3} Hz</td></tr>
        <tr><td>Embodied signal</td><td><span class="{embodied_class}">{embodied:?}</span> ({embodied_frame})</td></tr>
        <tr><td>Individual report</td><td><span class="{individual_class}">{individual:?}</span> ({individual_frame})</td></tr>
        <tr><td>Decision</td><td><span class="{result_class}">{result:?}</span> ({result_frame})</td></tr>
        <tr><td>ASI</td><td>{asi:.2}</td></tr>
        <tr><td>Reminders</td><td>{reminder_count}</td></tr>
    </table>

    {conflict_section}

    {attention_section}

    <h2>Reminder History</h2>
    <table>
        <tr><th>Time</th><th>Action</th><th>Target</th><th>Response</th></tr>
        {reminder_rows}
    </table>

    <footer>
        <p>Generated by Aurora v0.1.0 — M0 proof-of-concept. 不是指教，是提醒。</p>
    </footer>
</body>
</html>"#,
        scenario_id = "aurora_session",
        input_freq = report.input_freq,
        detected_freq = report.detected_freq,
        embodied_class = css_class(report.embodied.value()),
        embodied = report.embodied.value(),
        embodied_frame = report.embodied.frame(),
        individual_class = css_class(report.individual.value()),
        individual = report.individual.value(),
        individual_frame = report.individual.frame(),
        result_class = css_class(report.result.value()),
        result = report.result.value(),
        result_frame = report.result.frame(),
        asi = report.asi,
        reminder_count = report.reminder_count,
        conflict_section = conflict_section,
        attention_section = attention_section,
        reminder_rows = reminder_rows,
    )
}

fn css_class(value: TritValue) -> &'static str {
    match value {
        TritValue::True => "true",
        TritValue::False => "false",
        TritValue::Hold => "hold",
        TritValue::Unknown => "false",
    }
}

fn render_conflict_panel(report: &DecisionReport) -> String {
    match &report.interrupt {
        Some(interrupt) => format!(
            r#"<div class="conflict-panel">
    <h3>⚡ Conflict Panel — 冲突面板</h3>
    <p><strong>Conflict type:</strong> {:?}</p>
    <p><strong>Reason:</strong> {}</p>
    <p><strong>Structure:</strong> {} vs {}</p>
    <p style="color: #8b949e; font-style: italic;">
        💡 系统不替你判断哪个更"真实"。这是你的注意力被两个方向拉扯的信号。
    </p>
</div>"#,
            interrupt.conflict,
            interrupt.reason,
            report.embodied.frame(),
            report.individual.frame(),
        ),
        None => r#"<div class="no-conflict">
    <p>✅ No conflict detected — signals are aligned.</p>
</div>"#
            .to_string(),
    }
}

fn render_attention_section(report: &DecisionReport, session: &AttentionSession) -> String {
    let asi = session.asi();
    let asi_pct = (asi * 100.0) as u32;
    let bar_color = if asi > 0.6 {
        "#3fb950"
    } else if asi > 0.3 {
        "#d2991d"
    } else {
        "#f85149"
    };

    let cmd_text = match &report.attention_cmd {
        Some(cmd) => format!("{:?}", cmd),
        None => "Continue (no action needed)".into(),
    };

    format!(
        r#"<h2>Attention Sovereignty Index (ASI)</h2>
<div class="asi-gauge">
    <div class="asi-bar">
        <div class="asi-fill" style="width:{asi_pct}%; background:{bar_color};"></div>
    </div>
    <div class="asi-value" style="color:{bar_color};">{asi:.2}</div>
</div>
<p style="color: #8b949e;">
    ASI = 用户主动调度次数 / 系统提醒次数。越高 = 你越自主。
</p>
<p><strong>Last scheduler command:</strong> {cmd_text}</p>
<p><strong>Active shifts:</strong> {active} / <strong>Reminders:</strong> {total}</p>"#,
        asi_pct = asi_pct,
        bar_color = bar_color,
        asi = asi,
        cmd_text = cmd_text,
        active = session.user_active_shift_count(),
        total = session.reminder_count(),
    )
}

fn render_reminder_rows(session: &AttentionSession) -> String {
    session
        .reminders()
        .iter()
        .map(|r| {
            let (response_text, row_class) = match &r.user_response {
                Some(UserResponse::ShiftedTo(t)) => {
                    (format!("Shifted → {}", t), "shifted")
                }
                Some(UserResponse::OverrodeHold { chosen_frame }) => {
                    (format!("Overrode Hold → {}", chosen_frame), "shifted")
                }
                Some(UserResponse::Ignored) => ("Ignored".into(), "ignored"),
                Some(UserResponse::Dismissed) => ("Dismissed".into(), "ignored"),
                None => ("Pending".into(), "pending"),
            };
            format!(
                r#"<tr class="reminder {row_class}">
    <td>{time}</td><td>{action}</td><td>{target}</td><td>{response}</td>
</tr>"#,
                time = r.timestamp.format("%H:%M:%S"),
                action = r.action,
                target = r.target,
                response = response_text,
                row_class = row_class,
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}
